# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-05 12:00
from __future__ import unicode_literals

import activity.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to=activity.models.set_activity_image_upload_path, verbose_name='Image')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('statement', models.TextField(max_length=1000, verbose_name='Statement')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='City')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Kind', verbose_name='Kind')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activitys',
            },
        ),
        migrations.CreateModel(
            name='ActivityDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('document', models.FileField(upload_to=activity.models.set_activity_document_upload_path, verbose_name='Document')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Activity Document',
                'verbose_name_plural': 'Activity Documents',
            },
        ),
        migrations.CreateModel(
            name='ActivityLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('link', models.URLField(blank=True, max_length=300, null=True, verbose_name='Link')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Activity Link',
                'verbose_name_plural': 'Activity Links',
            },
        ),
        migrations.CreateModel(
            name='ActivityMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('coordinates', geoposition.fields.GeopositionField(max_length=42, verbose_name='Coordinates')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Activity Map',
                'verbose_name_plural': 'Activity Maps',
                'ordering': ('activity',),
            },
        ),
    ]
