# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-18 15:08
from __future__ import unicode_literals

import activity.models
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('coordinate', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='Coordinate')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('starting_date', models.DateField(verbose_name='Starting Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('starting_time', models.TimeField(verbose_name='Starting Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('wage_status', models.CharField(choices=[('0', 'Wage Earner'), ('1', 'Free')], max_length=10, verbose_name='Wage Status')),
                ('image', models.ImageField(blank=True, null=True, upload_to=activity.models.set_activity_image_upload_path, verbose_name='Image')),
                ('statement', models.TextField(max_length=1000, verbose_name='Statement')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_city', to='core.City', verbose_name='City')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Kind', verbose_name='Kind')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activitys',
            },
        ),
        migrations.CreateModel(
            name='ActivityDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('document', models.FileField(upload_to=activity.models.set_activity_document_upload_path, verbose_name='Document')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_documents', to='activity.Activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Activity Document',
                'verbose_name_plural': 'Activity Documents',
            },
        ),
        migrations.CreateModel(
            name='ActivityLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('link', models.URLField(null=True, verbose_name='Link')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_links', to='activity.Activity', verbose_name='Activity')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SocialAccount', verbose_name='Social Account')),
            ],
            options={
                'verbose_name': 'Activity Link',
                'verbose_name_plural': 'Activity Links',
            },
        ),
    ]
