# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-07 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=55, unique=True, verbose_name='City')),
                ('coordinate_city', geoposition.fields.GeopositionField(max_length=42, null=True, verbose_name='Coordinate')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'verbose_name': 'City',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50, unique=True, verbose_name='Kind')),
            ],
            options={
                'verbose_name_plural': 'Kinds',
                'verbose_name': 'Kind',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Social Account')),
                ('style_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Style Class')),
            ],
            options={
                'verbose_name_plural': 'Social Accounts',
                'verbose_name': 'Social Account',
            },
        ),
    ]
