# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-07 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=55, unique=True, verbose_name='City')),
                ('coordinat', geoposition.fields.GeopositionField(max_length=42, null=True, verbose_name='Coordinat')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50, unique=True, verbose_name='Kind')),
            ],
            options={
                'verbose_name': 'Kind',
                'verbose_name_plural': 'Kinds',
            },
        ),
    ]
