# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-12-07 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='coordinate_city',
        ),
    ]
